//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Input Maps/Player Inputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player Inputs"",
    ""maps"": [
        {
            ""name"": ""Speak"",
            ""id"": ""b2b3b434-8e4a-47bf-8f1a-4d958a598680"",
            ""actions"": [
                {
                    ""name"": ""Greet"",
                    ""type"": ""Button"",
                    ""id"": ""6218c1e8-f857-498b-a015-8a1b942459fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""18ffce48-2b5a-40af-8a71-50888d6fe761"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Greet"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Speak
        m_Speak = asset.FindActionMap("Speak", throwIfNotFound: true);
        m_Speak_Greet = m_Speak.FindAction("Greet", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Speak
    private readonly InputActionMap m_Speak;
    private List<ISpeakActions> m_SpeakActionsCallbackInterfaces = new List<ISpeakActions>();
    private readonly InputAction m_Speak_Greet;
    public struct SpeakActions
    {
        private @PlayerInputs m_Wrapper;
        public SpeakActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Greet => m_Wrapper.m_Speak_Greet;
        public InputActionMap Get() { return m_Wrapper.m_Speak; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SpeakActions set) { return set.Get(); }
        public void AddCallbacks(ISpeakActions instance)
        {
            if (instance == null || m_Wrapper.m_SpeakActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SpeakActionsCallbackInterfaces.Add(instance);
            @Greet.started += instance.OnGreet;
            @Greet.performed += instance.OnGreet;
            @Greet.canceled += instance.OnGreet;
        }

        private void UnregisterCallbacks(ISpeakActions instance)
        {
            @Greet.started -= instance.OnGreet;
            @Greet.performed -= instance.OnGreet;
            @Greet.canceled -= instance.OnGreet;
        }

        public void RemoveCallbacks(ISpeakActions instance)
        {
            if (m_Wrapper.m_SpeakActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISpeakActions instance)
        {
            foreach (var item in m_Wrapper.m_SpeakActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SpeakActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SpeakActions @Speak => new SpeakActions(this);
    public interface ISpeakActions
    {
        void OnGreet(InputAction.CallbackContext context);
    }
}
